### PR TITLE
Add code to handle booleans in objviz.

### PR DESCRIPTION
**Pull request by jwg4**
A simple fix for https://github.com/parrt/lolviz/issues/18

Let me know if any changes are needed.

### CODE REVIEW

**Comment by parrt** [comment]
Thanks! I might just do my own fix because I don't have a contributors license set up for this repository yet.

**Comment by jwg4** [comment]
Is there anything I can do to make this easier? I am happy to contribute all copyright, just would like to see this in the package.

**Comment by parrt** [comment]
Hi. Sorry for the delay. I guess this project is minor enough I don't have to worry about contributors license. merging.

**Comment by jwg4** [comment]
Thanks!

**Pull request merged**
